Repository remcom/hass-victron, pull requests merged in 2025-01, with the labels that each got.

#15 tweak ci flow and at ruff format check
  .github/workflows/hacs.yml
  .github/workflows/hassfest.yml
  .github/workflows/labels.yml
  .github/workflows/ruff.yml
  .github/workflows/stale.yaml 
Labels: ci

#21 Some minor documentation updates.
  README.md
Labels: documentation

#14 Update const.py
  custom_components/victron/const.py
Labels: enhancement

#22 Make integration work with pymodbus 3.7.4 or 3.8 and higher
  custom_components/victron/coordinator.py
  custom_components/victron/hub.py
Labels: enhancement

#23 First batch code cleanup pylint
  .pylintrc
  custom_components/victron/base.py
  custom_components/victron/binary_sensor.py
  custom_components/victron/button.py
  custom_components/victron/config_flow.py
  custom_components/victron/const.py
  custom_components/victron/hub.py
  custom_components/victron/number.py
  custom_components/victron/select.py
  custom_components/victron/sensor.py
Labels: enhancement

#28 Dont scan id 0 and allow all types for id 100
  custom_components/victron/const.py
  custom_components/victron/hub.py
Labels: enhancement

#31 Update ci flow
  .github/release-drafter.yml
  .github/workflows/build.yaml
  .github/workflows/release-drafter.yml
  .github/workflows/stale.yaml 
Labels: ci

#32 Dev/update ci flow
  .github/release-drafter.yml
Labels: ci

#29 Dev/update registers
  custom_components/victron/const.py
Labels: enhancement
